<?php
define("homeTitle", "WriteYourWays.org");
define("aboutTitle", "WriteYourWays.org : About");
define("servicesTitle", "WriteYourWays.org : Services");
define("contactTitle", "WriteYourWays.org : Contact");
define("historyTitle", "WriteYourWays.org : History");
define("privacyTitle", "WriteYourWays.org : Privacy Policy");
define("legalTitle", "WriteYourWays.org : Legal Disclaimer");
define("termsTitle", "WriteYourWays.org : Terms of Service");
?>